# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = "../hybrid_flutter"
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'hybrid_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hybrid_ios
  install_all_flutter_pods(flutter_application_path)

end
