name: flutter_app
description: A new Flutter application.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  bga_flutter_package: ^0.0.2
  transparent_image: ^2.0.0 # https://pub.flutter-io.cn/packages/transparent_image

  shelf_router: ^1.1.3 # https://pub.flutter-io.cn/packages/shelf_router
  dio: ^4.0.6 # https://pub.flutter-io.cn/packages/dio

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
