name: independent
description: Flutter Note
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.0 # https://pub.flutter-io.cn/packages/json_annotation
  english_words: ^3.1.5 # https://pub.flutter-io.cn/packages/english_words
  transparent_image: ^1.0.0 # https://pub.flutter-io.cn/packages/transparent_image
#  cached_network_image: ^1.1.2+1 # https://pub.flutter-io.cn/packages/cached_network_image
  http: ^0.12.0+2 # https://pub.flutter-io.cn/packages/http
  css_colors: ^1.0.2 # https://pub.flutter-io.cn/packages/css_colors
  url_launcher: ^5.2.5 # https://pub.flutter-io.cn/packages/url_launcher
  flutter_webview_plugin: ^0.3.8 # https://pub.flutter-io.cn/packages/flutter_webview_plugin
  webview_flutter: ^0.3.15+1 # https://pub.flutter-io.cn/packages/webview_flutter

dev_dependencies:
  build_runner: ^1.7.2 # https://pub.flutter-io.cn/packages/build_runner
  json_serializable: ^3.2.3 # 可以配置别名 alias genjson="flutter packages pub run build_runner build --delete-conflicting-outputs" https://pub.flutter-io.cn/packages/json_serializable
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/lake.jpg
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pavlova.jpg
    - images/container/pic1.jpg
    - images/container/pic2.jpg
    - images/container/pic3.jpg
    - images/container/pic4.jpg
    - images/grid/pic1.jpg
    - images/grid/pic2.jpg
    - images/grid/pic3.jpg
    - images/grid/pic4.jpg
    - images/grid/pic5.jpg
    - images/grid/pic6.jpg
    - images/grid/pic7.jpg
    - images/grid/pic8.jpg
    - images/grid/pic9.jpg
    - images/grid/pic10.jpg
    - images/grid/pic11.jpg
    - images/grid/pic12.jpg
    - images/grid/pic13.jpg
    - images/grid/pic14.jpg
    - images/grid/pic15.jpg
    - images/grid/pic16.jpg
    - images/grid/pic17.jpg
    - images/grid/pic18.jpg
    - images/grid/pic19.jpg
    - images/grid/pic20.jpg
    - images/grid/pic21.jpg
    - images/grid/pic22.jpg
    - images/grid/pic23.jpg
    - images/grid/pic24.jpg
    - images/grid/pic25.jpg
    - images/grid/pic26.jpg
    - images/grid/pic27.jpg
    - images/grid/pic28.jpg
    - images/grid/pic29.jpg
    - images/grid/pic30.jpg
    - images/no-data.png
    - images/loading.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
