name: bga_dart_note
description: Dart Note
version: 1.0.3
homepage: https://github.com/bingoogolapple/dart-note
author: bingoogolapple <bingoogolapple@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.5.1
  decimal: ^0.3.5
  shelf_static: ^0.2.8 # https://pub.flutter-io.cn/packages/shelf_static

  http_server: ^0.9.8+3 # https://pub.flutter-io.cn/packages/http_server

  http_multi_server: ^2.1.0 # https://pub.flutter-io.cn/packages/http_multi_server

  shelf_router: ^0.7.1 # https://pub.flutter-io.cn/packages/shelf_router

  dio: ^3.0.3 # https://github.com/flutterchina/dio

dev_dependencies:
  test: ^1.6.11
